add homework for lesson 2
LoraOrliGeo/IT-Talents-Season-11 pull request #1
Opened 2019-08-22 16:26 UTC by LoraOrliGeo

2019-08-23 07:36 UTC, grigorzyapkov requested changes

2019-08-23 07:36 UTC, grigorzyapkov commented on src/lesson2/Task1.java
> +        if (a < c && c < b){
c is between if c is in interval [a,b]

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task5.java
> +public class Task5 {
This is not correct. What if a=b and c is the largest number?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task1.java
> +        if (a < c && c < b){
c should be in interval [a,b]

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task7.java
> +            if (money > 0){
I think that here you should print "I will stay at home" doesn't matter if I have money or not

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task8.java
> +        int secondNum = Integer.parseInt(secondDigit + "" + thirdDigit);
It is better to use String.format("%d%d", fistDigit, secondDigit)

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task9.java
> +        if (lastDigit % 2 == 0){
Can you extract this into separate method called isEven()?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task10.java
> +            System.out.println("Additional bucket of " + (volume - total) + " liters");
It is not correct, try with volume=24

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task11.java
> +        if (number % decimals == 0 && number % tens == 0 && number % hundreds == 0){
Can you extract this into separated method?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task12.java
> +        if (((year % 4 == 0) && (year % 100 != 0) || (year % 400 == 0))) {
Can you extract this into separated method?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task12.java
> +            } else if (day < 31) {
What if the date is 30.02.2015?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task13.java
> +        if (temperature >= 25) {
Can you use switch instead?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task14.java
> +public class Task14 {
I think there is more simple solution for this task.

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task15.java
> +    public static void main(String[] args) {
Can you use switch or if-else structure. With this solution the program checks each if doesn't matter if the previous one is true. Can you extract each condition into separated method as well?

2019-08-23 07:36 UTC, grigorzyapkov commented on src/main/java/lesson2/Task16.java
> +        } else if (dec > tens && tens > hundreds){
Check the example in the task again. There is a little problem here. Can you extract each check into separate method?

2019-08-23 08:24 UTC, LoraOrliGeo commented on src/main/java/lesson2/Task12.java
> +            } else if (day < 31) {
The input has to be a valid date!

2019-08-23 08:26 UTC, LoraOrliGeo commented on src/main/java/lesson2/Task13.java
> +        if (temperature >= 25) {
NO! The switch-contruction check a single variable and its value! The cases of the switch are the different values that the variable may have, you can not put as a case a boolean expression.

2019-08-23 08:37 UTC, LoraOrliGeo commented on src/main/java/lesson2/Task7.java
> +            if (money > 0){
I think if you are sick and you have money, you have to go to the pharmacy and buy medicine (we assume that you don't have medicines at home).

2019-08-24 10:26 UTC, grigorzyapkov commented on src/main/java/lesson2/Task7.java
> +            if (money > 0){
Correct.

2019-08-24 10:27 UTC, grigorzyapkov commented on src/main/java/lesson2/Task8.java
> +        int secondNum = Integer.parseInt(secondDigit + "" + thirdDigit);
This statement is weird: secondDigit + "" + thirdDigit

2019-08-25 09:01 UTC, grigorzyapkov requested changes

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task10.java
> +        int equalTwoNThree = volume / 5;
Not an understandable name for variable. You can use numberOfCoursesWithTwoBuckets

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task10.java
> +                System.out.printf("Additional %d bucket/s of 3 liters%n", remain + 1);
You can print directly "Additional 2 bucket/s of 3 liters" because remain is equal to 1

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task10.java
> +                System.out.printf("Additional %d bucket/s of 2 liters%n", remain / 2);
remain will be 2 I think, you can check if remain == 2, and print message like above

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task10.java
> +        } else {
What if remain = 3? You can better use switch for all this cases

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task12.java
> +        if (((year % 4 == 0) && (year % 100 != 0) || (year % 400 == 0))) {
You can directly assign to variable isLeapYear the result of function isLeapYear which returns this complicated check

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task14.java
> +    static boolean cellsHaveSameColor(int firstCol, int secondCol) {
This function doesn't return if cells have same color. It return true if the given numbers are both even or odd.

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task14.java
>          } else {
not quite clear what is happening in this statement

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson2/Task16.java
> +        } else if (dec > tens && tens > hundreds){
There is a little problem here.

2019-08-25 09:01 UTC, grigorzyapkov commented on src/main/java/lesson3/Task8.java
> +                result += digit;
Its is better to use String builder here. StringBuilder result = new StringBuilder(); and result.append(digit);

2019-08-25 09:31 UTC, grigorzyapkov requested changes

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task9.java
> +        for (int i = a; i <= b ; i++) {
It's better to use while loop here. while(i <= b && sum <= 200)

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task9.java
> +            output.add(pow + "");
Use string format here.

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task11.java
> +        for (int i = 1; i < n; i+=2) {
Can you try to solve this task without nested loops?

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task12.java
> +            // add it to a collection and print the collection outside the for loop?
It is better to print them directly in the loop because you have to iterate through the collection of numbers that you have to print one more time, which slows the program.

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task13.java
> +            System.out.println("There is not a three-digit number that satisfies the condition!");
What about 100?

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task14.java
> +        int n = sc.nextInt();
Can you add the check if n is in interval [10,200]?

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task15.java
> +        do{
It is better to use for loop instead of do-while loop, because if n < 0 the do-while loop will be executed 1 time and the sum will be negative integer.

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task16.java
> +        for (int i = Math.max(a, b); i >= Math.min(a, b) ; i--) {
You can extract Math.max and Math.min because each time the program reach the for loop it will call this two functions for one same thing.

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task17.java
> +        //too many methods?
It is better because the program can be understand faster.

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task19.java
> +        while (prev > 1) {
I think that this should be while prev != 1

2019-08-25 09:31 UTC, grigorzyapkov commented on src/main/java/lesson3/Task20.java
> +            String row = "";
Can you use StringBuilder instead of String?

2019-08-25 09:46 UTC, grigorzyapkov requested changes

2019-08-25 09:46 UTC, grigorzyapkov commented on src/main/java/lesson3/Task21.java
> +                cardName = index + 2 + "";
Use String.fomrat here

2019-08-25 09:46 UTC, grigorzyapkov commented on src/main/java/lesson3/Task21.java
> +        String cardName = "";
No need to assign empty string.

2019-08-25 09:46 UTC, grigorzyapkov commented on src/main/java/lesson3/Task24.java
> +        do {
If you use for loop this solution will looks more simple.

2019-08-25 09:46 UTC, grigorzyapkov commented on src/main/java/lesson3/Task25.java
> +        if (number > 0) {
No need of this check.

2019-08-28 16:35 UTC, merged