Classes and objects
LoraOrliGeo/IT-Talents-Season-11 pull request #4
Opened 2019-09-26 05:49 UTC by LoraOrliGeo

2019-09-28 11:13 UTC, grigorzyapkov requested changes

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        return matcher.find();
Are you sure that this will return false if number="0885953420 abvasd"

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +    void insertSimCard(String simMobileNumber) {
You should add a message if the number is not valid.

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        hasSimCard = false;
It is a good practice to use this when you refer to class fields: this.hasSimCard = false;

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        boolean isSameNumber = receiver.simMobileNumber.equals(this.simMobileNumber);
This can throw NullPointerException if the receiver is null or if receiver.simMobileNumber is null. It is better to use Objects.equals(receiver.simMobileNumber, this.simMobileNumber)

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        if (!validateParameters(receiver, duration)) {
You should add message why the call wasn't successfull

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        call.receiver = receiver;
You should set call caller property

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/Call.java
> +    static double priceForAMinute;
can you rename priceForAMinute to pricePerMinute and make it constant with initial value

2019-09-28 11:13 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +public class GSM {
You have a missing methods printInfoForTheLastOutgoingCall() printInfoForTheLastIncomingCall()

2019-09-28 11:58 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        return matcher.find();
![regex](https://user-images.githubusercontent.com/49145113/65816102-58d8ee80-e200-11e9-9bca-1dba57a83f82.png)

2019-09-28 11:59 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +    void insertSimCard(String simMobileNumber) {
In the problem's description it's not specified that it should print a message. And it's not a good practice to print directly in the method... 
Although, I added a message.

2019-09-28 12:01 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        hasSimCard = false;
Yes, I know, but we didn't talk about "this" in lectures, that's why I didn't use it.

2019-09-28 12:20 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        boolean isSameNumber = receiver.simMobileNumber.equals(this.simMobileNumber);
I added a conditional statement if the receiver is null.

2019-09-28 12:20 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        call.receiver = receiver;
done

2019-09-28 12:20 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +        if (!validateParameters(receiver, duration)) {
If I add a message why the call is invalid, the "validateParameters" method in its form now will be unnecessary to exists. Otherwise I should move the whole validation in this if-statement and the call-method will do two things and it's not good practise.

2019-09-28 12:20 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/Call.java
> +    static double priceForAMinute;
I would if we takled about constants in lecture

2019-09-28 12:20 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2/GSM.java
> +public class GSM {
done

2019-10-04 15:34 UTC, grigorzyapkov requested changes

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task1/Computer.java
> +            }
you should return 0 if prices are the same and c is not null

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task1/Computer.java
> +        return 0;
you should throw exception or return value different from -1, 0, 1

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +            boolean haveFreeSpaces = this.freeSpaces <= this.students.length && this.freeSpaces > 0;
this.freeSpaces will always be <= 5, you can simply check if it is > 0

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +                this.students[this.students.length - freeSpaces] = s;
Use STUDENTS_IN_GROUP instead of this.students.length

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +        this.students = new Student[STUDENTS_IN_GROUP];
You can call emptyGroup here

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +        double bestGrade = this.students[0].getGrade();
This can throw NullPointerException if this.students[0] = 0, use bestGrade = 0 as initial value

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +        for (int i = 0; i < this.students.length; i++) {
You can simply iterate to STUDENTS_IN_GROUP - freeSpaces

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task_employee/Task.java
> +    String getName() {
This getter should be public

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task_employee/Task.java
> +    int getWorkingHours() {
This getter should be public

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task_employee/Employee.java
> +            int employeeHours = this.hoursLeft;
You simply can use this.hoursLeft, instead of assigning it to variable

2019-10-04 15:34 UTC, grigorzyapkov commented on src/main/java/module_two/lesson13_classes_objects/task_employee/Employee.java
> +            }
You have to call showReport here

2019-10-04 16:33 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task_employee/Employee.java
> +            int employeeHours = this.hoursLeft;
It's more readable with variables

2019-10-04 16:35 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +        this.students = new Student[STUDENTS_IN_GROUP];
Every time a StudentGroup is created, the number of students is STUDENTS_IN_GROUP and the array of Students has the same initial lenght.

2019-10-04 16:39 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task1/Computer.java
> +            }
done

2019-10-04 16:40 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task1/Computer.java
> +        return 0;
done

2019-10-04 16:41 UTC, LoraOrliGeo commented on src/main/java/module_two/lesson13_classes_objects/task2_students/StudentGroup.java
> +            boolean haveFreeSpaces = this.freeSpaces <= this.students.length && this.freeSpaces > 0;
done

2019-10-04 17:17 UTC, merged